name: carilaundry2
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  animated_bottom_navigation_bar: ^0.3.2
  get: ^4.6.5
  app_settings: ^5.0.0
  carousel_slider: ^4.2.1
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.3
  device_info_plus: ^9.1.2
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_icons_null_safety: ^1.1.0
  flutter_local_notifications: ^17.2.3
  flutter_screenutil: ^5.0.0+2
  google_fonts: ^6.2.1
  http: ^1.1.0
  http_parser: ^4.0.2
  image_picker: ^1.0.4
  intl: ^0.20.2
  lucide_icons: ^0.257.0
  path_provider: ^2.0.11
  permission_handler: ^11.1.0
  provider: ^6.1.2
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.11
  clipboard: ^0.1.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  assets:
    - assets/images/logo.png
    - assets/images/agian.png
    - assets/images/fanya.png
    - assets/images/illustration.png

  uses-material-design: true
