// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPKRMZ_zbJcPghOBZyuG9FTWwXCLdelQI',
    appId: '1:988731056473:web:9ede92b82f1a7076636c48',
    messagingSenderId: '988731056473',
    projectId: 'cari-laundry-30f43',
    authDomain: 'cari-laundry-30f43.firebaseapp.com',
    storageBucket: 'cari-laundry-30f43.firebasestorage.app',
    measurementId: 'G-Z5TZ6VWVT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0ZXX9Simir2F99b5kbM9YIccYd6wfpUg',
    appId: '1:988731056473:android:01136955ace25bd6636c48',
    messagingSenderId: '988731056473',
    projectId: 'cari-laundry-30f43',
    storageBucket: 'cari-laundry-30f43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9cz-yACgT9QsVJkMpyQfCC-VI1BiuQ6s',
    appId: '1:988731056473:ios:bf164b5ec071202e636c48',
    messagingSenderId: '988731056473',
    projectId: 'cari-laundry-30f43',
    storageBucket: 'cari-laundry-30f43.firebasestorage.app',
    iosBundleId: 'com.example.cariLaundry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9cz-yACgT9QsVJkMpyQfCC-VI1BiuQ6s',
    appId: '1:988731056473:ios:bf164b5ec071202e636c48',
    messagingSenderId: '988731056473',
    projectId: 'cari-laundry-30f43',
    storageBucket: 'cari-laundry-30f43.firebasestorage.app',
    iosBundleId: 'com.example.cariLaundry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPKRMZ_zbJcPghOBZyuG9FTWwXCLdelQI',
    appId: '1:988731056473:web:6dc6c60eb7c57ab6636c48',
    messagingSenderId: '988731056473',
    projectId: 'cari-laundry-30f43',
    authDomain: 'cari-laundry-30f43.firebaseapp.com',
    storageBucket: 'cari-laundry-30f43.firebasestorage.app',
    measurementId: 'G-2NBRD3YBET',
  );

}